export const GameConstant = {
    SCREEN_WIDTH: 512,
    SCREEN_HEIGHT: 512,
    X_HEALTH_BAR: 30,
    Y_HEALTH_BAR: 480,
    HEALTH_BAR_WIDTH: 140,
    HEALTH_BAR_HEIGHT: 10,
    X_MESS: 100,
    Y_MESS: 220,
    BLOB_WIDTH: 32,
    BLOB_HEIGHT: 32,
    SPACING: 48,
    NUM_BLOB: 6,
    X_OFF_SET: 150,
    VY_BLOB: 1.5,
    WALL_WIDTH: 32,
    X_DOOR: 32,
    Y_DOOR: 0,
    DOOR_WIDTH: 32,
    DOOR_HEIGHT: 32,
    X_TREASURE: 512 - 30,
    Y_TREASURE: 512 / 2 - 32,
    TREASURE_WIDTH: 32,
    TREASURE_HEIGHT: 32,
    X_EXPLORER: 32,
    Y_EXPLORER: 512 / 2 - 32,
    EXPLORER_WIDTH: 32,
    EXPLORER_HEIGHT: 32,
    EXPLORER_MOVE: 3,
    BLOB_IMAGE: "blob.png",
    DOOR_IMAGE: "door.png",
    DUNGEON_IMAGE: "dungeon.png",
    EXPLORER_IMAGE: "explorer.png",
    TREASURE_IMAGE: "treasure.png",
    width : 10,
    height : 10,
    DEBUG_COLLIDER: false,
}
export const RECT_COLLIDER = 'rect';